/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domainmodel.Anh;
import domainmodel.ChiTietSP;
import domainmodel.DanhMuc;
import domainmodel.DongSP;
import domainmodel.MauSac;
import domainmodel.SanPham;
import domainmodel.Size;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import repository.SanPhamRepository;
import service.DongspService;
import service.ISizeService;
import service.MausacService;
import service.impl.DongspServiceimpl;
import service.impl.MausacServiceimpl;
import service.impl.SizeServiceiml1;
import service.DanhMucService;
import service.IAnhService;
import service.SanphamService;
import service.impl.AnhService;
import service.impl.DanhMucServiceimpl;
import service.impl.SanphamServiceimpl;
import viewmodel.SanphamProduct;

/**
 *
 * @author Admin
 */
public class FrmSanPham extends javax.swing.JFrame {

    DefaultTableModel defaultTable = new DefaultTableModel();
    /**
     * Creates new form FrmHome
     */


    List<SanphamProduct> listSanpham = new ArrayList<>();
    List<MauSac> listMausac = new ArrayList<>();
    List<DongSP> listDongsp = new ArrayList<>();
    List<Size> listSize = new ArrayList<>();
    List<DanhMuc> listDanhmuc = new ArrayList<>();
    List<Anh> listAnh = new ArrayList<>();

    MausacService service_mausac = new MausacServiceimpl();
    DongspService service_dongsp = new DongspServiceimpl();
    ISizeService service_size = new SizeServiceiml1();
    DanhMucService service_danhmuc = new DanhMucServiceimpl();
//    
    SanphamService service_sanpham = new SanphamServiceimpl();

    IAnhService service_anh = new AnhService();

    public FrmSanPham() {
        initComponents();

        listSanpham = service_sanpham.getAllSp();
        listDongsp = service_dongsp.getListDongsp();
        listMausac = service_mausac.getListMausac();
        listSize = service_size.getall();
        listDanhmuc = service_danhmuc.getDanhMucs();
        listAnh = service_anh.getListAnh();
//        

        cboDongsp.setModel(new DefaultComboBoxModel(listDongsp.toArray()));
        cboMausac.setModel(new DefaultComboBoxModel(listMausac.toArray()));
        cboSize.setModel(new DefaultComboBoxModel(listSize.toArray()));
        cboDanhmuc.setModel(new DefaultComboBoxModel(listDanhmuc.toArray()));

        fillSanpham();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanpham = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtTensp = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cboMausac = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txtNambh = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtMaSp = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        btnMausac = new javax.swing.JButton();
        cboDanhmuc = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        cboDongsp = new javax.swing.JComboBox<>();
        btnDongsp = new javax.swing.JButton();
        cboSize = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        btnChon = new javax.swing.JButton();
        txtAnh = new javax.swing.JTextField();
        txtSoluong1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        cboTrangthai = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextArea();
        lblMausac = new javax.swing.JLabel();
        lblDongsp1 = new javax.swing.JLabel();
        lblDanhmuc1 = new javax.swing.JLabel();
        lblanh = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phầm mềm bán giày");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 168, 133));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("QUẢN LÍ SẢN PHẨM");

        tblSanpham.setBackground(new java.awt.Color(204, 255, 255));
        tblSanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sp", "Tên sp", "Ảnh", "Mô tả", "Đơn giá", "Số lượng", "Dòng sp", "Size", "Danh mục", "Màu", "Năm BH", "Trạng thái"
            }
        ));
        tblSanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanpham);

        btnDelete.setText("DELETE");

        btnNew.setText("NEW");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");

        jButton5.setText(">|");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("|<");

        jButton7.setText("<<");

        jButton8.setText(">>");

        jLabel17.setText("Giá:");

        jLabel18.setText("Tên SP:");

        jLabel15.setText("Dòng sp:");

        jLabel19.setText("Danh mục:");

        jLabel21.setText("Mã SP:");

        jLabel22.setText("-");

        jLabel23.setText("-");

        jLabel24.setText("-");

        jLabel25.setText("Số lượng:");

        jLabel26.setText("-");

        lblSize.setText("-");

        jLabel28.setText("Mô tả");

        jButton10.setText("+");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btnMausac.setText("+");
        btnMausac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMausacActionPerformed(evt);
            }
        });

        cboDanhmuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel29.setText("Màu sắc:");

        btnDongsp.setText("+");
        btnDongsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongspActionPerformed(evt);
            }
        });

        cboSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel30.setText("Năm BH:");

        jButton13.setText("+");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        btnChon.setText("Chon ảnh");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        jLabel31.setText("Size:");

        cboTrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hoat động", "Dừng hoạt động" }));

        txtMota.setEditable(false);
        txtMota.setColumns(20);
        txtMota.setRows(5);
        jScrollPane2.setViewportView(txtMota);

        lblMausac.setText("-");

        lblDongsp1.setText("-");

        lblDanhmuc1.setText("-");

        lblanh.setText("ẢNH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblanh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnChon)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19)
                    .addComponent(jLabel29))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(cboDongsp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDongsp1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDanhmuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMausac, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMausac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDongsp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMausac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel25)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30)
                    .addComponent(jLabel28))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaSp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoluong1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNambh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnNew)
                .addGap(31, 31, 31)
                .addComponent(btnSave)
                .addGap(19, 19, 19)
                .addComponent(btnUpdate)
                .addGap(23, 23, 23)
                .addComponent(btnDelete)
                .addGap(87, 87, 87)
                .addComponent(cboTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jButton6)
                .addGap(17, 17, 17)
                .addComponent(jButton7)
                .addGap(11, 11, 11)
                .addComponent(jButton8)
                .addGap(11, 11, 11)
                .addComponent(jButton5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblanh, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChon)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel18)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel17)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel15)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel19)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel23)
                        .addGap(4, 4, 4)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel22)
                        .addGap(14, 14, 14)
                        .addComponent(cboDongsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblDongsp1)
                        .addGap(14, 14, 14)
                        .addComponent(cboDanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lblDanhmuc1)
                        .addGap(4, 4, 4)
                        .addComponent(cboMausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblMausac))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnDongsp)
                        .addGap(35, 35, 35)
                        .addComponent(jButton10)
                        .addGap(25, 25, 25)
                        .addComponent(btnMausac))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel21)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel25)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel31)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel30)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtMaSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel24)
                        .addGap(4, 4, 4)
                        .addComponent(txtSoluong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addGap(4, 4, 4)
                        .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lblSize)
                        .addGap(14, 14, 14)
                        .addComponent(txtNambh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton13)))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNew)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(cboTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton5)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 0, 950, 680));

        jPanel2.setBackground(new java.awt.Color(248, 210, 155));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 60));

        jPanel3.setBackground(new java.awt.Color(248, 230, 200));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 196, 255)));
        jPanel3.setPreferredSize(new java.awt.Dimension(120, 42));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sdf.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel3.setText("Bán Hàng");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 50));

        jPanel4.setBackground(new java.awt.Color(248, 230, 200));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 196, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel5.setText("Log Out");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-logout-rounded-32.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, 50));

        jPanel6.setBackground(new java.awt.Color(239, 168, 133));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 196, 255)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sản Phẩm");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-open-box-32.png"))); // NOI18N
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 50));

        jPanel5.setBackground(new java.awt.Color(248, 230, 200));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 196, 255)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel7.setText("Sản Phẩm");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hg.png"))); // NOI18N
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 50));

        jPanel7.setBackground(new java.awt.Color(248, 230, 200));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 196, 255)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel11.setText("Sản Phẩm");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hg.png"))); // NOI18N
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 50));

        jPanel8.setBackground(new java.awt.Color(248, 230, 200));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 196, 255)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel13.setText("Sản Phẩm");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hg.png"))); // NOI18N
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void fillSanpham() {
        defaultTable.setRowCount(0);
        defaultTable = (DefaultTableModel) tblSanpham.getModel();
        for (SanphamProduct sp : listSanpham) {
            defaultTable.addRow(new Object[]{sp.getIdSp(), sp.getTensp(), sp.getAnh(), sp.getMoTa(), sp.getGia(), sp.getSoluong(),
                sp.getIdDongsp(), sp.getIdSize(), sp.getMaDanhmuc(), sp.getIdMausac(), sp.getThoiGianBH()});
        }

    }


    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        FrmHome frmHome = new FrmHome();
        frmHome.show();
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnDongspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongspActionPerformed
        // TODO add your handling code here:
        Dongspview d = new Dongspview();
        d.setVisible(true);
    }//GEN-LAST:event_btnDongspActionPerformed

    private void btnMausacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMausacActionPerformed
        // TODO add your handling code here:
        Mausacview vi = new Mausacview();
        vi.setVisible(true);
    }//GEN-LAST:event_btnMausacActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        ViewSize s = new ViewSize();
        s.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    byte[] urlimage = null;
    String filename = null;
    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        txtAnh.setText(filename);
        lblanh.setIcon(new ImageIcon(f.toString()));
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            byte[] byt = new byte[1024];
            for (int i; (i = fis.read(byt)) != -1;) {
                baos.write(byt, 0, i);
            }
            urlimage = baos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnChonActionPerformed

    SanPham themsanpham() {
        return new SanPham(txtMaSp.getText(), txtTensp.getText());
    }

    SanphamProduct themctsp() {
        return new SanphamProduct(
                //                ((DanhMuc) cboDanhmuc.getSelectedItem()).getMaDanhMuc(),
                //                ((MauSac) cboMausac.getSelectedItem()).getId(),

                //                ((DongSP) cboDongsp.getSelectedItem()).getId(),
                //                
                //                
                //                Double.parseDouble(txtGia.getText()),
                txtMota.getText(),
                Double.parseDouble(txtGia.getText()),
                ((Size) cboSize.getSelectedItem()).getId(),
                ((MauSac) cboMausac.getSelectedItem()).getId(),
                ((DongSP) cboDongsp.getSelectedItem()).getId(),
                ((DanhMuc) cboDanhmuc.getSelectedItem()).getMaDanhMuc(),
                //                Integer.parseInt(txtSoluong1.getText()),
                Integer.parseInt(txtNambh.getText()),
                Integer.parseInt(txtSoluong1.getText())
        );
    }

//    Anh themanh(){
//         Anh a = new Anh();
////         a.setTen(txtTensp.getText());
//        String anh = txtAnh.getText();
//        anh = anh.replace("//", "////");
//        a.setUrlImage(urlimage);
//        
//       return null;
//    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Anh a = new Anh();
        a.setTen(txtTensp.getText());
        String anh = txtAnh.getText();
        anh = anh.replace("//", "////");
        a.setUrlImage(urlimage);
        listAnh.add(a);
        service_anh.them(a);
        JOptionPane.showMessageDialog(this, service_sanpham.insert(themsanpham(), themctsp()));
        listSanpham = service_sanpham.getAllSp();
        fillSanpham();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        DanhMucView dm = new DanhMucView();
        dm.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        txtAnh.setText("");
        txtMaSp.setText("");
        txtTensp.setText("");
        txtGia.setText("");
        txtSoluong1.setText("");
        txtNambh.setText("");
        lblanh.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private void tblSanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanphamMouseClicked
        // TODO add your handling code here:
        int index = tblSanpham.getSelectedRow();
        txtMaSp.setText(tblSanpham.getValueAt(index, 0).toString());
        txtTensp.setText(tblSanpham.getValueAt(index, 1).toString());
//        txtAnh.setText(tblSanpham.getValueAt(index, 2).toString());
        txtGia.setText(tblSanpham.getValueAt(index, 4).toString());
        txtSoluong1.setText(tblSanpham.getValueAt(index, 5).toString());

        byte[] image = (listAnh.get(index).getUrlImage());
        ImageIcon icon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(lblanh.getWidth(), lblanh.getHeight(), Image.SCALE_SMOOTH));
        lblanh.setIcon(icon);

        if (tblSanpham.getValueAt(index, 6) == null) {
            lblDongsp1.setText("Sản phẩm không có mã dòng sản phẩm ");
        } else {
            lblDongsp1.setText("");
            for (int j = 0; j < listDongsp.size(); j++) {
                if (listDongsp.get(j).getTen().equals(tblSanpham.getValueAt(index, 6).toString())) {
                    cboDongsp.setSelectedIndex(j);
                }
            }
        }
//        
//        if (tblSanpham.getValueAt(index, 7) == null) {
//            lblSize.setText("Sản phẩm không có size ");
//        } else {
//            lblSize.setText("");
//            for (int j = 0; j < listSize.size(); j++) {
//                if (listSize.get(j).getSoSize().equals(tblSanpham.getValueAt(index, 7).toString())) {
//                    cboSize.setSelectedIndex(j);
//                }
//            }
//        }
        cboSize.setSelectedItem(tblSanpham.getValueAt(index, 7).toString());

//         
        if (tblSanpham.getValueAt(index, 8) == null) {
            lblDanhmuc1.setText("Sản phẩm không có mã danh mục ");
        } else {
            lblDanhmuc1.setText("");
            for (int j = 0; j < listDanhmuc.size(); j++) {
                if (listDanhmuc.get(j).getTen().equals(tblSanpham.getValueAt(index, 8).toString())) {
                    cboDanhmuc.setSelectedIndex(j);
                }
            }
        }
        txtNambh.setText(tblSanpham.getValueAt(index, 10).toString());

//
//       
        if (tblSanpham.getValueAt(index, 9) == null) {
            lblMausac.setText("Sản phẩm không có màu sắc ");
        } else {
            lblMausac.setText("");
            for (int j = 0; j < listMausac.size(); j++) {
                if (listMausac.get(j).getTen().equals(tblSanpham.getValueAt(index, 9).toString())) {
                    cboMausac.setSelectedIndex(j);
                }
            }
        }
        
        txtMota.setText(tblSanpham.getValueAt(index,3).toString());
    }//GEN-LAST:event_tblSanphamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmSanPham().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDongsp;
    private javax.swing.JButton btnMausac;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboDanhmuc;
    private javax.swing.JComboBox<String> cboDongsp;
    private javax.swing.JComboBox<String> cboMausac;
    private javax.swing.JComboBox<String> cboSize;
    private javax.swing.JComboBox<String> cboTrangthai;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDanhmuc1;
    private javax.swing.JLabel lblDongsp1;
    private javax.swing.JLabel lblMausac;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblanh;
    private javax.swing.JTable tblSanpham;
    private javax.swing.JTextField txtAnh;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaSp;
    private javax.swing.JTextArea txtMota;
    private javax.swing.JTextField txtNambh;
    private javax.swing.JTextField txtSoluong1;
    private javax.swing.JTextField txtTensp;
    // End of variables declaration//GEN-END:variables

}
